services:
  - type: web
    name: fake-news-detector
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python download_model.py
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
